extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/member-ordering': error
